# ============================
# Application Configuration
# ============================
spring:
  application:
    name: base-api

# ============================
# Server Configuration
# ============================
server:
  port: 8080
  servlet:
    context-path: /base-api

# ============================
# Actuator Configuration
# ============================
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,metrics,loggers
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

# ============================
# Application Info
# ============================
info:
  app:
    name: ${spring.application.name}
    description: Base API - Spring Boot Template
    version: 0.0.1-SNAPSHOT
    java:
      version: 25

# ============================
# H2 Console Configuration
# ============================
spring.h2.console:
  enabled: true
  path: /h2-console

# ============================
# Logging Configuration
# ============================
logging:
  level:
    root: INFO
    com.ar.laboratory: INFO

